name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
  FIREBASE_AUTHDOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
  FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
  FIREBASE_STORAGEBUCKET: ${{ secrets.FIREBASE_STORAGEBUCKET }}
  FIREBASE_MESSAGINSENDERID: ${{ secrets.FIREBASE_MESSAGINSENDERID }}
  FIREBASE_APPID: ${{ secrets.FIREBASE_APPID }}
  VERCEL_URL: ${{ secrets.VERCEL_URL }}
  CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
  GITHUB_CLIENT_SECRETS: ${{ secrets.GITHUB_CLIENT_SECRETS }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRETS: ${{ secrets.GOOGLE_CLIENT_SECRETS }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Set Firebae API Key as Environment Variable
        run: echo "FIREBASE_APIKEY=${{ secrets.FIREBASE_APIKEY }}" >> .env
      - name: Set Firebae Auth Domain as Environment Variable
        run: echo "FIREBASE_AUTHDOMAIN=${{ secrets.FIREBASE_AUTHDOMAIN }}" >> .env
      - name: Set Firebae Project ID as Environment Variable
        run: echo "FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }}" >> .env
      - name: Set Firebae Storage Bucket as Environment Variable
        run: echo "FIREBASE_STORAGEBUCKET=${{ secrets.FIREBASE_STORAGEBUCKET }}" >> .env
      - name: Set Firebae Messaging Sender ID as Environment Variable
        run: echo "FIREBASE_MESSAGINSENDERID=${{ secrets.FIREBASE_MESSAGINSENDERID }}" >> .env
      - name: Set Firebae App ID as Environment Variable
        run: echo "FIREBASE_APPID=${{ secrets.FIREBASE_APPID }}" >> .env
      - name: Set Vercel URL as Environment Variable
        run: echo "VERCEL_URL=${{ secrets.VERCEL_URL }}" >> .env
      - name: Set Callback URL as Environment Variable
        run: echo "CALLBACK_URL=${{ secrets.CALLBACK_URL }}" >> .env
      - name: Set NextAuth URL as Environment Variable
        run: echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
      - name: Set NextAuth Secret as Environment Variable
        run: echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
      - name: Set Github Client ID as Environment Variable
        run: echo "GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}" >> .env
      - name: Set Github Client Secrets as Environment Variable
        run: echo "GITHUB_CLIENT_SECRETS=${{ secrets.GITHUB_CLIENT_SECRETS }}" >> .env
      - name: Set Google Client ID as Environment Variable
        run: echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
      - name: Set Google Client Secrets as Environment Variable
        run: echo "GOOGLE_CLIENT_SECRETS=${{ secrets.GOOGLE_CLIENT_SECRETS }}" >> .env
      - name: Set MongoDB URI as Environment Variable
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
